token length can be set
Erwane/cakephp-token pull request #6
Opened 2021-04-06 15:25 UTC by rrd108

I think it would be a better approach to let the user set the token length

2021-04-06 15:46 UTC, Erwane commented
Thanks, really nice idea.

2021-04-07 16:35 UTC, rrd108 commented
Will you merge the pr?

2021-04-07 21:21 UTC, Erwane commented
Yes i will but please fix little things i comment please.

2021-04-08 13:30 UTC, Erwane requested changes

2021-04-08 13:30 UTC, Erwane commented on src/Model/Table/TokensTable.php
> +    public function generate(array $content = [], $expire = null, $tokenLength = null): string
should be `int $tokenLength = 8` because `_uniqId($length)` require an int

2021-04-08 13:30 UTC, Erwane commented on src/Model/Table/TokensTable.php
> +    protected function _uniqId($length): string
the type is missing. `int $length`

2021-04-08 13:30 UTC, Erwane commented on src/Token.php
> +    public static function generate(array $content = [], string $expire = null, int $tokenLength = null): string
Should be `8`, not `null`

2021-04-08 13:30 UTC, merged